// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhflpqusuexinfwmibgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoZmxwcXVzdWV4aW5md21pYmd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTQ2ODIsImV4cCI6MjA3MDEzMDY4Mn0.3MwJuh9tt_JxxCGU--M0vtW7U2_opZyvolufDJAN17s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});